name: GitForm Processor
on:
  repository_dispatch:
    types: [gitform_submission]

jobs:
  process-form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create data file
        run: |
          mkdir -p data
          echo '${{ toJSON(github.event.client_payload.formData) }}' > data/${{ github.event.client_payload.filename }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new feedback: ${{ github.event.client_payload.filename }}"
          title: "新反馈提交：${{ github.event.client_payload.filename }}"
          body: "来自 ${{ github.event.client_payload.formData.name }} 的反馈"
          branch: "feedback-${{ github.run_id }}"
